/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminGateRouteRouteImport } from './routes/admin/_gate/route'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AnimalsIndexRouteImport } from './routes/animals/index'
import { Route as AnimalsAnimalIdRouteImport } from './routes/animals/$animalId'
import { Route as AdminGateAnimalCardsRouteImport } from './routes/admin/_gate/animal-cards'
import { Route as AdminGateAnimalsRouteImport } from './routes/admin/_gate/animals'
import { Route as AdminGateBookingsRouteImport } from './routes/admin/_gate/bookings'
import { Route as AdminGateBreedsRouteImport } from './routes/admin/_gate/breeds'
import { Route as AdminGateContactRouteImport } from './routes/admin/_gate/contact'
import { Route as AdminGateContentRouteImport } from './routes/admin/_gate/content'
import { Route as AdminGateDashboardRouteImport } from './routes/admin/_gate/dashboard'
import { Route as AdminGateGalleryRouteImport } from './routes/admin/_gate/gallery'
import { Route as AdminGateServicesRouteImport } from './routes/admin/_gate/services'
import { Route as AdminGateSettingsRouteImport } from './routes/admin/_gate/settings'
import { Route as ApiPublicMediaSplatRouteImport } from './routes/api/public/media/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGateRouteRoute = AdminGateRouteRouteImport.update({
  id: '/admin/_gate',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimalsIndexRoute = AnimalsIndexRouteImport.update({
  id: '/animals/',
  path: '/animals/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimalsAnimalIdRoute = AnimalsAnimalIdRouteImport.update({
  id: '/animals/$animalId',
  path: '/animals/$animalId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGateAnimalCardsRoute = AdminGateAnimalCardsRouteImport.update({
  id: '/animal-cards',
  path: '/animal-cards',
  getParentRoute: () => AdminGateRouteRoute,
} as any)
const AdminGateAnimalsRoute = AdminGateAnimalsRouteImport.update({
  id: '/animals',
  path: '/animals',
  getParentRoute: () => AdminGateRouteRoute,
} as any)
const AdminGateBookingsRoute = AdminGateBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminGateRouteRoute,
} as any)
const AdminGateBreedsRoute = AdminGateBreedsRouteImport.update({
  id: '/breeds',
  path: '/breeds',
  getParentRoute: () => AdminGateRouteRoute,
} as any)
const AdminGateContactRoute = AdminGateContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AdminGateRouteRoute,
} as any)
const AdminGateContentRoute = AdminGateContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminGateRouteRoute,
} as any)
const AdminGateDashboardRoute = AdminGateDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminGateRouteRoute,
} as any)
const AdminGateGalleryRoute = AdminGateGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminGateRouteRoute,
} as any)
const AdminGateServicesRoute = AdminGateServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminGateRouteRoute,
} as any)
const AdminGateSettingsRoute = AdminGateSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminGateRouteRoute,
} as any)
const ApiPublicMediaSplatRoute = ApiPublicMediaSplatRouteImport.update({
  id: '/api/public/media/$',
  path: '/api/public/media/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminGateRouteRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/animals/$animalId': typeof AnimalsAnimalIdRoute
  '/admin/': typeof AdminIndexRoute
  '/animals/': typeof AnimalsIndexRoute
  '/admin/animal-cards': typeof AdminGateAnimalCardsRoute
  '/admin/animals': typeof AdminGateAnimalsRoute
  '/admin/bookings': typeof AdminGateBookingsRoute
  '/admin/breeds': typeof AdminGateBreedsRoute
  '/admin/contact': typeof AdminGateContactRoute
  '/admin/content': typeof AdminGateContentRoute
  '/admin/dashboard': typeof AdminGateDashboardRoute
  '/admin/gallery': typeof AdminGateGalleryRoute
  '/admin/services': typeof AdminGateServicesRoute
  '/admin/settings': typeof AdminGateSettingsRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminIndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/animals/$animalId': typeof AnimalsAnimalIdRoute
  '/animals': typeof AnimalsIndexRoute
  '/admin/animal-cards': typeof AdminGateAnimalCardsRoute
  '/admin/animals': typeof AdminGateAnimalsRoute
  '/admin/bookings': typeof AdminGateBookingsRoute
  '/admin/breeds': typeof AdminGateBreedsRoute
  '/admin/contact': typeof AdminGateContactRoute
  '/admin/content': typeof AdminGateContentRoute
  '/admin/dashboard': typeof AdminGateDashboardRoute
  '/admin/gallery': typeof AdminGateGalleryRoute
  '/admin/services': typeof AdminGateServicesRoute
  '/admin/settings': typeof AdminGateSettingsRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/_gate': typeof AdminGateRouteRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/animals/$animalId': typeof AnimalsAnimalIdRoute
  '/admin/': typeof AdminIndexRoute
  '/animals/': typeof AnimalsIndexRoute
  '/admin/_gate/animal-cards': typeof AdminGateAnimalCardsRoute
  '/admin/_gate/animals': typeof AdminGateAnimalsRoute
  '/admin/_gate/bookings': typeof AdminGateBookingsRoute
  '/admin/_gate/breeds': typeof AdminGateBreedsRoute
  '/admin/_gate/contact': typeof AdminGateContactRoute
  '/admin/_gate/content': typeof AdminGateContentRoute
  '/admin/_gate/dashboard': typeof AdminGateDashboardRoute
  '/admin/_gate/gallery': typeof AdminGateGalleryRoute
  '/admin/_gate/services': typeof AdminGateServicesRoute
  '/admin/_gate/settings': typeof AdminGateSettingsRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/login'
    | '/animals/$animalId'
    | '/admin/'
    | '/animals/'
    | '/admin/animal-cards'
    | '/admin/animals'
    | '/admin/bookings'
    | '/admin/breeds'
    | '/admin/contact'
    | '/admin/content'
    | '/admin/dashboard'
    | '/admin/gallery'
    | '/admin/services'
    | '/admin/settings'
    | '/api/public/media/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin/login'
    | '/animals/$animalId'
    | '/animals'
    | '/admin/animal-cards'
    | '/admin/animals'
    | '/admin/bookings'
    | '/admin/breeds'
    | '/admin/contact'
    | '/admin/content'
    | '/admin/dashboard'
    | '/admin/gallery'
    | '/admin/services'
    | '/admin/settings'
    | '/api/public/media/$'
  id:
    | '__root__'
    | '/'
    | '/admin/_gate'
    | '/admin/login'
    | '/animals/$animalId'
    | '/admin/'
    | '/animals/'
    | '/admin/_gate/animal-cards'
    | '/admin/_gate/animals'
    | '/admin/_gate/bookings'
    | '/admin/_gate/breeds'
    | '/admin/_gate/contact'
    | '/admin/_gate/content'
    | '/admin/_gate/dashboard'
    | '/admin/_gate/gallery'
    | '/admin/_gate/services'
    | '/admin/_gate/settings'
    | '/api/public/media/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminGateRouteRoute: typeof AdminGateRouteRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AnimalsAnimalIdRoute: typeof AnimalsAnimalIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AnimalsIndexRoute: typeof AnimalsIndexRoute
  ApiPublicMediaSplatRoute: typeof ApiPublicMediaSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_gate': {
      id: '/admin/_gate'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminGateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animals/': {
      id: '/animals/'
      path: '/animals'
      fullPath: '/animals/'
      preLoaderRoute: typeof AnimalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animals/$animalId': {
      id: '/animals/$animalId'
      path: '/animals/$animalId'
      fullPath: '/animals/$animalId'
      preLoaderRoute: typeof AnimalsAnimalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_gate/animal-cards': {
      id: '/admin/_gate/animal-cards'
      path: '/animal-cards'
      fullPath: '/admin/animal-cards'
      preLoaderRoute: typeof AdminGateAnimalCardsRouteImport
      parentRoute: typeof AdminGateRouteRoute
    }
    '/admin/_gate/animals': {
      id: '/admin/_gate/animals'
      path: '/animals'
      fullPath: '/admin/animals'
      preLoaderRoute: typeof AdminGateAnimalsRouteImport
      parentRoute: typeof AdminGateRouteRoute
    }
    '/admin/_gate/bookings': {
      id: '/admin/_gate/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminGateBookingsRouteImport
      parentRoute: typeof AdminGateRouteRoute
    }
    '/admin/_gate/breeds': {
      id: '/admin/_gate/breeds'
      path: '/breeds'
      fullPath: '/admin/breeds'
      preLoaderRoute: typeof AdminGateBreedsRouteImport
      parentRoute: typeof AdminGateRouteRoute
    }
    '/admin/_gate/contact': {
      id: '/admin/_gate/contact'
      path: '/contact'
      fullPath: '/admin/contact'
      preLoaderRoute: typeof AdminGateContactRouteImport
      parentRoute: typeof AdminGateRouteRoute
    }
    '/admin/_gate/content': {
      id: '/admin/_gate/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminGateContentRouteImport
      parentRoute: typeof AdminGateRouteRoute
    }
    '/admin/_gate/dashboard': {
      id: '/admin/_gate/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminGateDashboardRouteImport
      parentRoute: typeof AdminGateRouteRoute
    }
    '/admin/_gate/gallery': {
      id: '/admin/_gate/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGateGalleryRouteImport
      parentRoute: typeof AdminGateRouteRoute
    }
    '/admin/_gate/services': {
      id: '/admin/_gate/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminGateServicesRouteImport
      parentRoute: typeof AdminGateRouteRoute
    }
    '/admin/_gate/settings': {
      id: '/admin/_gate/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminGateSettingsRouteImport
      parentRoute: typeof AdminGateRouteRoute
    }
    '/api/public/media/$': {
      id: '/api/public/media/$'
      path: '/api/public/media/$'
      fullPath: '/api/public/media/$'
      preLoaderRoute: typeof ApiPublicMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminGateRouteRouteChildren {
  AdminGateAnimalCardsRoute: typeof AdminGateAnimalCardsRoute
  AdminGateAnimalsRoute: typeof AdminGateAnimalsRoute
  AdminGateBookingsRoute: typeof AdminGateBookingsRoute
  AdminGateBreedsRoute: typeof AdminGateBreedsRoute
  AdminGateContactRoute: typeof AdminGateContactRoute
  AdminGateContentRoute: typeof AdminGateContentRoute
  AdminGateDashboardRoute: typeof AdminGateDashboardRoute
  AdminGateGalleryRoute: typeof AdminGateGalleryRoute
  AdminGateServicesRoute: typeof AdminGateServicesRoute
  AdminGateSettingsRoute: typeof AdminGateSettingsRoute
}

const AdminGateRouteRouteChildren: AdminGateRouteRouteChildren = {
  AdminGateAnimalCardsRoute: AdminGateAnimalCardsRoute,
  AdminGateAnimalsRoute: AdminGateAnimalsRoute,
  AdminGateBookingsRoute: AdminGateBookingsRoute,
  AdminGateBreedsRoute: AdminGateBreedsRoute,
  AdminGateContactRoute: AdminGateContactRoute,
  AdminGateContentRoute: AdminGateContentRoute,
  AdminGateDashboardRoute: AdminGateDashboardRoute,
  AdminGateGalleryRoute: AdminGateGalleryRoute,
  AdminGateServicesRoute: AdminGateServicesRoute,
  AdminGateSettingsRoute: AdminGateSettingsRoute,
}

const AdminGateRouteRouteWithChildren = AdminGateRouteRoute._addFileChildren(
  AdminGateRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminGateRouteRoute: AdminGateRouteRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AnimalsAnimalIdRoute: AnimalsAnimalIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  AnimalsIndexRoute: AnimalsIndexRoute,
  ApiPublicMediaSplatRoute: ApiPublicMediaSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
